### ISSUE TITLE
ARM架构中出现多次"非指定客户端"错误后才会认证成功

### ISSUE THREAD

**Issue by sequencer** [hyrathb/mentohust#265]
如题,
树莓派ubuntu&archlinux测试
地点在紫菘12
欢迎上门测试(

**Comment by hyrathb** [comment]
回家了，年后吧……

**Comment by sequencer** [comment]
PrPr

**Comment by mtunique** [comment]
@hyrathb  没回家  快约他 他在沁园

**Comment by updateing** [comment]
R7000，Linux 2.6.36.4，uClibc 0.9.32.1

'printf("%02x", (char)0x98);' 得到'98'

同样的语句在Ubuntu 15.10，Linux 4.2.0-27，glibc 2.21得到'ffffff98'

这样的语句目前发现在'checkV4.c'的'case 0'中有出现。也许这是问题所在吧……

**Comment by sequencer** [comment]
我在raspberry pi archlinux,貌似在每个case中都有问题.
你看看是不是能解决?
我住在校外去了,没法调试了_(:з」∠)_

**Comment by updateing** [comment]
我现在不能复现问题了……

在进入case之前还有两个转换也有问题，它们会影响到算法的选择。这里修复了吗？

**Comment by sequencer** [comment]
我中午回去试试

**Comment by hyrathb** [comment]
oh, thanks. 不过signed char和char有区别吗？现在我也有时间看一下了。

**Comment by hyrathb** [comment]
好吧，确实char的实现跟编译器有关……如果没有修复的话，就reopen吧。
