### ISSUE TITLE
server返回消息乱码的问题

### ISSUE THREAD

**Issue by stelectronic** [hyrathb/mentohust#271]
服务器返回的消息serverMsg字符串应该改变下编码方式, 现在是中文显示乱码

虽然不是大问题, 不影响认证成功, 还是可以改进下

至于是哪种编码就不知道了, 我猜是GBK...大神可以去试试

**Comment by updateing** [comment]
这里是有采用libiconv的，编译时若能找到iconv.h即会自动开启编码转换支持，从而显示正确的文字。

注意有些工具链里会带一个stub形式的iconv.h，啥事都不干。如果有的话要记得删掉，

**Comment by stelectronic** [comment]
我是小白⊙﹏⊙没有在工具链里发现icon.h, 怎么回事?

**Comment by updateing** [comment]
工具链里没有的话，可以另外下载libiconv的源码编译出来，再用`CFLAGS=-I... LIBS=...`来configure MentoHUST即可。

相关代码在这里：https://github.com/hyrathb/mentohust/blob/master/src/myfunc.c#L71

**Comment by hyrathb** [comment]
多谢关注，最近还是忙……既然问题在别处，就先关闭了。

**Comment by stelectronic** [comment]
我需要交叉编译用在openwrt中的话, libiconv是用ubuntu下的工具链编译,还是用openwrt的工具链编译呢?

**Comment by updateing** [comment]
也需要使用OpenWrt的工具链来交叉编译……

**Comment by stelectronic** [comment]
@updateing 怎么交叉编译libiconv用在openwrt上...configure命令怎么写...

**Comment by updateing** [comment]
https://github.com/updateing/mentohust/blob/master/BuildGuide.md#building-for-openwrt-1404--mips

相比MentoHUST的交叉编译并没有什么特殊的。`--help`已经很详细了。
