### ISSUE TITLE
checkv4.c里的两个array是哪里提取?

### ISSUE THREAD

**Issue by ivechan** [hyrathb/mentohust#272]
你好,我本来想把该V4程序用在我的学校上.
经过调试发现ComputePWD函数正确,而ComputeV4函数不正确,发现可能是v4.c里声明的array不一样.
不知道Hu Yunrui同学能否告知一二

**Comment by sequencer** [comment]
ComputeV4需要反编译得到

**Comment by ivechan** [comment]
谢谢,刚刚用蠢方法解决了这个问题.
顺便感谢下hyrathb提供的算法.

**Comment by hyrathb** [comment]
那个数组在linux版（单文件）中似乎叫做dll_data和app_data。
windows版中我还没有研究在哪个文件里。
这两个数组其实应该是可以配置的，等我忙完了改一下。

**Comment by updateing** [comment]
如果要做参数的话，可以考虑引入长选项了……现在26个字母都要用完了😂

**Comment by ShanQincheng** [comment]
想问一下 @ivechan 用了什么方法解决了checkV4两个数组的问题，我是在我们学校Linux版锐捷里面提取的，尽管我们学校Linux版锐捷是无法认证成功的......但数组确实是对的

另外还想问一下，你如何调试知道ComputerPWD函数是正确的？

谢谢

**Comment by ivechan** [comment]
@ShanQincheng 就是提取，没有别的办法。
用原生锐捷登录抓包后，把包里数据 加密后和锐捷发的包对比就可以验证加密函数是否正确了。

**Comment by ShanQincheng** [comment]
@ivechan 好的谢谢，貌似你就是中山的Jing。
现在我自己的账号已经可以正常登录了，但是换别人的账号就提示‘请使用管理员指定的客户端’，并且在认证失败的日志中看到ipv4地址居然是我的，不是别人账号的。

正版锐捷发送的包里，还有一段0x10 bit的数据，和一段0x20 bit的数据是每次都变化的，但是我的Mentohust里面是固定的，也就是我抓下来的三个pk数组里，那一次的数据，在不停重复地用。我看了源代码，里面没有其他更改这两段数据的代码了，所以我对这两段数据有些无能为力。

再加上我更改了源代码里好些其它的认证数据位置的偏移量。我推测我们学校的锐捷认证和华科，中山的大不一样。还得再研究研究，才能弄出本校学生通用的版本。呼~
