### ISSUE TITLE
厚脸皮再来询问一个问题,心跳包验证不能通过

### ISSUE THREAD

**Issue by ivechan** [hyrathb/mentohust#273]
我将V4版本适配到我的学校(主要是改pkt,array两个参数)后,发现已经能正常通过验证了.
但是原来的心跳包验证好像不能通过.
找到原来作者的开发wiki中,有提到心跳包需要解密加密..不知道有没有好心人能提供下思路?

**Comment by ivechan** [comment]
已经有点头绪,正在草稿验证..期待好消息

**Comment by ivechan** [comment]
已经搞定了，发在这里希望能帮助到其他人。
1. _Sucess_包 的 _echoKey_ 的offset发生变化
2.  需要指定初始的 _echoNo_ ,一般不从0开始
3. 心跳包加密解密算法没有改变。（刚开始以为变化了，苦逼地在草稿纸上写0101算了半天）

**Comment by stelectronic** [comment]
@ivechan 你好, 这代码还需要针对学校修改吗, 为什么我使用认证会出现“用户不允许使用本服务”, 请问有何解...

**Comment by nature2608** [comment]
@ivechan 能否在代码中指出需要修改的地方？“_Sucess_包 的 echoKey 的offset发生变化”  这个变化会怎么样？“需要指定初始的 echoNo ,一般不从0开始” 怎么看是不是从0开始？

**Comment by ivechan** [comment]
@nature2608 这个修改版，主要代码都在 myfun.c 里，其他文件大部分是旧版本的历史文件。
1. 在 getEchoKey 函数中有一个变量名为 offset，原作者也注释了这样代码，这是通过抓包获取的，不同学校不一样。
2. echoNo 通过抓 Success 包，然后通过加密方法逆推，应该就能得到。心跳包我记得加密方法只是简单的位操作然后进行+1操作。

不过我写这个代码已经是2年前了，全凭印象，而且不同学校的认证方法不一定一致，甚至已经升级，所以仅供参考。

**Comment by nature2608** [comment]
@ivechan 我看了一下没有找出来，我把抓包放上来能否帮我分析一下？我用的是学校linux客户端和@ysc3839 改良的minieap进行的抓包，根据ysc3839反编译的结果是心跳代码不完全，不能发送心跳包，可我看了一下我的是发送出去的，字段格式也对，可能计算不对，6分钟就断线。能否帮我看一下，谢谢。

[抓包.zip](https://github.com/hyrathb/mentohust/files/1943241/default.zip)

**Comment by ivechan** [comment]
@nature2608 不好意思, 我现在正忙于论文, 暂时没有时间. 抱歉.

**Comment by nature2608** [comment]
@ivechan 好嘞，谢谢
