### ISSUE TITLE
系统提示: 用户不允许使用本服务!

### ISSUE THREAD

**Issue by stelectronic** [hyrathb/mentohust#275]
RT, 在mipsel上运行成功, 但是显示"用户不允许使用本服务", 这是什么原因呢, 同一个账号我用官方的锐捷客户端可以认证的

**Comment by hyrathb** [comment]
这个需要更具体点的日志，不过我现在觉得是你没有用-s指定服务吧。

**Comment by stelectronic** [comment]
-s参数怎么使用，-h里没看关于到-s的使用呀

**Comment by stelectronic** [comment]
s参数不是指定DNS的么。。？

**Comment by updateing** [comment]
1. 官方Linux客户端可以认证吗？
2. 官方客户端无误的话，请抓包。

**Comment by stelectronic** [comment]
我这学校把internet服务和default服务换着用的...mentohust应该默认用的是internet服务吧..
@updateing 抓包是在linux下抓还是在windows下抓?
@hyrathb 你说的-s指定服务可以指定为default服务吗, 具体怎么使用呢?

**Comment by updateing** [comment]
@stelectronic 请不要一个问题重复发表，会变成邮件洪水的。
我是说确认官方Linux客户端认证通过以后再尝试抓MentoHUST的包。

你可以尝试移植 https://github.com/HustLion/mentohust/pull/267 当然能修改为参数指定服务名的话最好。

**Comment by ivechan** [comment]
这个版本的mentohust是解决了V4验证的问题。但没有适配其他学校（华科以外）的锐捷。
所以其他学校使用可能需要自己抓包，然后修改。算法都是相同的。

**Comment by stelectronic** [comment]
@ivechan 我抓过包，然后-f指定mpf数据文件，最后总是提示数据文件无效(⊙_⊙)。

**Comment by ivechan** [comment]
@stelectronic 这里抓包不是说用mentohust tools抓,不是为了让你使用mpf,就这个版本来说,并没有提供mpf功能等各种自定义功能.
这里说抓包是为了看哪里出错了.
抓包可以用wireshark,在filter输入eap||eapol确定可以过滤非锐捷验证包.
建议你把mentohust和锐捷的包一起抓.
因为密码是不可逆算法加密的,所以一般情况不用担心包会泄露你的密码

**Comment by weiguang** [comment]
可以使用wireshark抓包，发出看一下

**Comment by hyrathb** [comment]
恩现在已经有修改服务名的功能了。

**Comment by ShanQincheng** [comment]
默认的认证方式是Internet，我们学校这种默认方式就不行，得改成教育网。但是改了之后提示依然不行，没有发送ip地址给服务器

**Comment by updateing** [comment]
修改服务名和发送IP地址有什么联系吗？

**Comment by ShanQincheng** [comment]
没有联系，这是两个我认为无法用Mentohust连接锐捷成功的原因。

我用V3算法版本的Mentohust验证，返回V2,V3效验值，然后提示‘请使用管理员指定的客户端’。我用这个V4算法版本的Mentohust验证，没有发送ip地址，也没有发送服务地区(我在我们学校网络中心看到的)，所以无法验证成功。

V3算法版本的Mentohust发送了服务地区与ip地址

**Comment by ivechan** [comment]
锐捷是通过dhcp向服务器获得地址，没有向服务器发送地址这一说。
你可以看看是不是dhcp过程出现问题了。

**Comment by ShanQincheng** [comment]
十分感谢你们的回复。我再研究研究，对这方面之前从没接触过，突然看到一堆源代码有些手足无措

**Comment by updateing** [comment]
有些地方确实是会有向服务器提交地址这个说法的。我校如果用`-d2`（认证后DHCP），虽然能认证成功并正常上网，但在管理中心看到的认证在线IP地址是0.0.0.0. 用官方客户端时，这里就是DHCP得到的正确地址。（相应地，如果使用代理认证方法，这里会显示路由器分给电脑的内网IP地址）

考虑到这个issue已经关闭，且你的问题与此无关，建议新开一个issue，参考[这里](https://github.com/hyrathb/mentohust/issues/280#issuecomment-247516982)来提交抓包以便分析。

**Comment by ivechan** [comment]
看的懂源码的话，可以去看看EAP协议，用wireshark抓包检查

**Comment by ShanQincheng** [comment]
谢谢。待我去研究研究。

**Comment by hyrathb** [comment]
锐捷确实有不使用DHCP的模式，需要向服务器提交ip地址，此功能现在没有加入这个版本的mentohust，请新开一个issue。
