### ISSUE TITLE
手工交叉编译出现问题

### ISSUE THREAD

**Issue by factoid0** [hyrathb/mentohust#277]
提示cannot find input file 'makefile.in'

**Comment by updateing** [comment]
请贴出`git clone`以后所有执行的命令及结果。

**Comment by factoid0** [comment]
你好，打扰您了，手动交叉编译遇到问题，各种google 百度解决不了，我是直接下载的源码（https://github.com/HustLion/mentohust的加入V4支持的版本），后 unzip解压 cd到mentohust-master 目录，toolchain是从openwrt网站下载的（ https://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/OpenWrt-SDK-ar71xx-generic_gcc-5.3.0_musl-1.1.14.Linux-x86_64.tar.bz2）

然后在 gedit ~/.bashrc 添加了环境变量：
export PATH=$PATH:/home/factoid/temp/OpenWrt-SDK-ar71xx-generic_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/bin
export CC=mips-openwrt-linux-gcc  
export CPP=mips-openwrt-linux-cpp  
export GCC=mips-openwrt-linux-gcc  
export CXX=mips-openwrt-linux-g++  
export RANLIB=mips-openwrt-linux-uclibc-ranlib  
export ac_cv_linux_vers=2.6.24  
export LDFLAGS="-static"  
export CFLAGS="-Os -s"  
export STAGING_DIR=/home/factoid/temp/OpenWrt-SDK-ar71xx-generic_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14
后source ./bashrc 

然后就这样了：
factoid@Lenovo-G400:~/temp/test/HustLion-mentohust-6c74178$ sh autogen.sh
+ autopoint
autogen.sh: 4: autogen.sh: autopoint: not found
+ aclocal
+ autoheader
+ automake --add-missing
configure.ac:19: installing './compile'
configure.ac:6: installing './config.guess'
configure.ac:59: error: required file './config.rpath' not found
configure.ac:6: installing './config.sub'
configure.ac:7: installing './install-sh'
configure.ac:7: installing './missing'
Makefile.am: installing './INSTALL'
Makefile.am: installing './COPYING' using GNU General Public License v3 file
Makefile.am:     Consider adding the COPYING file to the version control system
Makefile.am:     for your code, to avoid questions about which license your project uses
configure.ac:59: error: required file './ABOUT-NLS' not found
src/Makefile.am: installing './depcomp'
+ autoconf

factoid@Lenovo-G400:~/temp/test/HustLion-mentohust-6c74178$ ./configure --host=mips-openwrt-linux --disable-encodepass --disable-arp --disable-notify --disable-nls
checking build system type... x86_64-pc-linux-gnu
checking host system type... mips-openwrt-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for mips-openwrt-linux-strip... mips-openwrt-linux-strip
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for mips-openwrt-linux-gcc... mips-openwrt-linux-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... yes
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether mips-openwrt-linux-gcc accepts -g... yes
checking for mips-openwrt-linux-gcc option to accept ISO C89... none needed
checking whether mips-openwrt-linux-gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of mips-openwrt-linux-gcc... gcc3
checking how to run the C preprocessor... mips-openwrt-linux-cpp
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking whether byte ordering is bigendian... yes
checking for dlsym in -ldl... yes
checking for a sed that does not truncate output... /bin/sed
checking whether NLS is requested... no
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for ld used by mips-openwrt-linux-gcc... /home/factoid/temp/OpenWrt-SDK-ar71xx-generic_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/mips-openwrt-linux-musl/bin/ld
checking if the linker (/home/factoid/temp/OpenWrt-SDK-ar71xx-generic_gcc-5.3.0_musl-1.1.14.Linux-x86_64/staging_dir/toolchain-mips_34kc_gcc-5.3.0_musl-1.1.14/mips-openwrt-linux-musl/bin/ld) is GNU ld... yes
checking for shared library run path origin... /bin/bash: ./config.rpath: No such file or directory
done
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking whether to use NLS... no
checking iconv.h usability... yes
checking iconv.h presence... yes
checking for iconv.h... yes
checking arpa/inet.h usability... yes
checking arpa/inet.h presence... yes
checking for arpa/inet.h... yes
checking fcntl.h usability... yes
checking fcntl.h presence... yes
checking for fcntl.h... yes
checking netinet/in.h usability... yes
checking netinet/in.h presence... yes
checking for netinet/in.h... yes
checking for stdint.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking sys/ioctl.h usability... yes
checking sys/ioctl.h presence... yes
checking for sys/ioctl.h... yes
checking sys/socket.h usability... yes
checking sys/socket.h presence... yes
checking for sys/socket.h... yes
checking sys/time.h usability... yes
checking sys/time.h presence... yes
checking for sys/time.h... yes
checking for unistd.h... (cached) yes
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for size_t... yes
checking for atexit... yes
checking for memmove... yes
checking for memset... yes
checking for socket... yes
checking for strrchr... yes
checking for setlocale... yes
config result: host(linux-gnu) pcap(dyload) notify(no) encode(no) arp(no) nls(no)
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: error: cannot find input file: `Makefile.in


谢谢您了

**Comment by factoid0** [comment]
是我没装什么依赖包吗？还是我下载的TOOLCHAIN有问题？

**Comment by updateing** [comment]
```
factoid@Lenovo-G400:~/temp/test/HustLion-mentohust-6c74178$ sh autogen.sh

autopoint autogen.sh: 4: autogen.sh: autopoint: not found
aclocal
autoheader
automake --add-missing configure.ac:19: installing './compile' configure.ac:6: installing './config.guess' configure.ac:59: error: required file './config.rpath' not found configure.ac:6: installing './config.sub' configure.ac:7: installing './install-sh' configure.ac:7: installing './missing' Makefile.am: installing './INSTALL' Makefile.am: installing './COPYING' using GNU General Public License v3 file Makefile.am: Consider adding the COPYING file to the version control system Makefile.am: for your code, to avoid questions about which license your project uses configure.ac:59: error: required file './ABOUT-NLS' not found src/Makefile.am: installing './depcomp'
autoconf
```
参考 https://github.com/HustLion/mentohust/blob/master/BuildGuide.md
```
sudo apt-get install autopoint
sudo apt-get install automake
sudo apt-get install autoconf
sudo apt-get install gettext
```
此外，建议用`CFLAGS=xxx ./configure --host=xxx ...`的方式来使用交叉编译，而不是直接写死GCC等全局生效的环境变量。这在上面的BuildGuide都有。

**Comment by factoid0** [comment]
谢谢哈，我研究研究来自我的华为手机-------- 原始邮件 --------主题：Re: [hyrathb/mentohust] 手工交叉编译出现问题 (#277)发件人：Hamster Tian 收件人：hyrathb/mentohust 抄送：factoid0 ,Manual factoid@Lenovo-G400:~/temp/test/HustLion-mentohust-6c74178$ sh autogen.sh

autopoint autogen.sh: 4: autogen.sh: autopoint: not found
aclocal
autoheader
automake --add-missing configure.ac:19: installing './compile' configure.ac:6: installing './config.guess' configure.ac:59: error: required file './config.rpath' not found configure.ac:6: installing './config.sub' configure.ac:7: installing './install-sh' configure.ac:7: installing './missing' Makefile.am: installing './INSTALL' Makefile.am: installing './COPYING' using GNU General Public License v3 file Makefile.am: Consider adding the COPYING file to the version control system Makefile.am: for your code, to avoid questions about which license your project uses configure.ac:59: error: required file './ABOUT-NLS' not found src/Makefile.am: installing './depcomp'
autoconf


参考 https://github.com/HustLion/mentohust/blob/master/BuildGuide.md

sudo apt-get install autopoint
sudo apt-get install automake
sudo apt-get install autoconf
sudo apt-get install gettext


此外，建议用CFLAGS=xxx ./configure --host=xxx ...的方式来使用交叉编译，而不是直接写死GCC等全局生效的环境变量。这在上面的BuildGuide都有。

**Comment by factoid0** [comment]
谢谢，问题解决了
