### ISSUE TITLE
聚聚有想法重构么

### ISSUE THREAD

**Issue by sequencer** [hyrathb/mentohust#281]
啊 一直觉着这项目有重构的需求...
图形界面的需求...
要是聚聚有重构的想法的话...
我可以写Mac的UI...
现在项目看的太蛋疼了...

**Comment by hyrathb** [comment]
重构当然是坠吼的啊，毕竟我当时只花了两个星期搞了一个能用的版本。不过恐怕我得等到明年四五月份才闲得下来啊。我先试着找找有没有人愿意接锅吧。

**Comment by sequencer** [comment]
啊 两个星期两周看了这么多汇编orz
主要是我现在住外面没测试环境...
等明年进组的时候在办公区再调试吧...
现在如果有人重构...我能写下mac下的UI...

**Comment by hyrathb** [comment]
sad，看来要等一段时间了。

**Comment by etnperlong** [comment]
支持，我们学校限制很多，估计这条路还有很长
