### ISSUE TITLE
不兼容旧版mentohust吗？

### ISSUE THREAD

**Issue by keysona** [hyrathb/mentohust#284]
我是使用arch的，首先在aur下了这个mentohust，但是验证通不过。

开始是提示，”用户不在服务。。“，加了```--service dianxin```。

然后是提示”不可以使用的客户端。。。“，已经把三个必要的文件放在```/etc/mentohust```了。

还是一样的错误，尝试调整版本号```-v 4.4```。

最后是在window下使用mentohustTool抓了一个mpf包，```-f data.mpf```

还是一样的错误，”不可以使用的客户端。。。“

就去下了旧版的mentohust，google code仓库那个。

这次使用加上```-v 4.4```，就顺利通过验证了。

是我学校的锐捷太老了吗？还是新版的不兼容？

**Comment by hyrathb** [comment]
是的，现在还不兼容旧版本认证方式。

**Comment by keysona** [comment]
原来如此，搞了一天原来是版本兼容问题。:cry:

已更新了archlinux wiki。安装小节那里放了一个旧版本mentohust的地址，顺便提了下兼容问题。

**Comment by hyrathb** [comment]
好的，谢谢。
