### ISSUE TITLE
用户不允许使用本服务

### ISSUE THREAD

**Issue by Gabirel** [hyrathb/mentohust#286]
我加了`--service 联通`之后，就会这样：
```log
>> looking for server...
V4 type: 0
** Server MAC:	00:1a:a9:17:ff:ff
>>sending username...
V4 type: 0
>>sending password...
V4 type: 1
>> Authentication failed!
$$ Server Messsage:	用户不允许使用本服务!
!! cannot load libnotify, please check its existence.
** Server MAC:	00:1a:a9:17:ff:ff
>>sending username...
V4 type: 0
>>sending password...
V4 type: 2
>> Authentication failed!
$$ Server Messsage:	用户不允许使用本服务!
** Server MAC:	00:1a:a9:17:ff:ff
>>sending username...
V4 type: 0
>>sending password...
V4 type: 1
>> Authentication failed!
$$ Server Messsage:	用户不允许使用本服务!
** Server MAC:	00:1a:a9:17:ff:ff
>>sending username...
V4 type: 0
>> looking for server...
V4 type: 0
>>sending username...
V4 type: 0
>>sending password...
V4 type: 4
>> Authentication failed!
$$ Server Messsage:	用户不允许使用本服务!

```

请问这样要怎么处理？

**Comment by updateing** [comment]
用iconv转成GBK编码，不带末尾回车。也可以在Windows版的抓包里找到服务名的十六进制表示，用`echo -ne`赋给参数。

**Comment by Gabirel** [comment]
关于前一种，能不能给个具体操作呢？
> echo "联通" | iconv -f UTF8 -t GBK
这种出来的结果我怎么传递给mentohust？

**Comment by updateing** [comment]
试试这样：

```
--service `echo -n 联通 | iconv -f utf8 -t gbk`
```

**Comment by Gabirel** [comment]
还是不可以，直接切换到了校园网了，无法读取到联通的服务

**Comment by updateing** [comment]
那就只能抓包了。在官方客户端的抓包里，查找这个十六进制串：

```
1a 28 00 00 13 11 39 22
```

然后看看后面跟着的0x20个字节是什么内容。

**Comment by Gabirel** [comment]
是后面这串内容：
> c1 aa cd a8
![screenshot_2016-12-03_20-05-26](https://cloud.githubusercontent.com/assets/12933851/20859245/885a6aac-b91e-11e6-9fc1-c25c916c86a0.png)

`联通`的十六进制不是么：
>80 54 90 1a

难道是GBK编码？

**Comment by updateing** [comment]
```
# echo -n 联通|iconv -f utf8 -t gbk|hexdump -C
00000000  c1 aa cd a8                                       |....|
```

这跟最开始的iconv做参数是一样的结果。我稍后测试一下MentoHUST是否正确发出了这四个字节。

**Comment by updateing** [comment]
用这个试试？ https://github.com/hyrathb/mentohust/pull/287

**Comment by Gabirel** [comment]
额，我不知道这个正不正确，但是，有发错误：
```log
** net card[1]:	enp1s0
** net card[2]:	wlp2s0
** net card[5]:	bluetooth0
** net card[6]:	bluetooth-monitor
** net card[7]:	nflog
** net card[8]:	nfqueue
** net card[9]:	usbmon1
** net card[10]:	usbmon2
** net card[11]:	usbmon3
?? enter net card[1-11]:1
** net card [1] selected.
** username:	20141XXXXXX
** net card:	enp1s0
** 服务名:	��ͨ
** authenticate timeout:	8 sec(s)
** heartbeat interval:	30 sec(s)
** wait on failure:	15 sec(s)
** failure allowed:	8 time(s)
** multicast address:	standard
** DHCP type:	not in used
** notify timeout:	5 sec(s)
** localhost mac:	34:17:XX:5b:XX:XX
** using IP:	10.19.16.89
** netmask:	255.255.240.0
** authenticate parameters saved to /etc/mentohust.conf.
>> looking for server...
V4 type: 0
** Server MAC:	00:1a:a9:17:ff:ff
>>sending username...
V4 type: 0
>>sending password...
V4 type: 0
>> Authentication failed!
$$ Server Messsage:	不允许使用的客户端类型!
!! cannot load libnotify, please check its existence.
** Server MAC:	00:1a:a9:17:ff:ff
>>sending username...
V4 type: 0
>>sending password...
V4 type: 4
>> Authentication failed!
$$ Server Messsage:	不允许使用的客户端类型!
^C>> Authentication exited.
```

**Comment by updateing** [comment]
这个可能是学校不支持Linux客户端吧……比较麻烦了

**Comment by Gabirel** [comment]
天哪～～我们学校提供的Linux客户端也是这个问题
> 不允许使用的客户端类型

真的没有解决办法了么

**Comment by Gabirel** [comment]
> 不允许使用的客户端类型

问题已解决，跟学校信息中心说过了，他们应该是服务端对客户端类型做了限制。学校那边解除了这个限制，就没问题了。


不过，衍生出另一个问题，
> sudo mentohust --service $SERVICE -w

再执行，
> sudo mentohust 

服务名仍然无法保存下来啊？有没有什么解决办法？

**Comment by updateing** [comment]
试试 #289

**Comment by Gabirel** [comment]
我看了这个commit # [30198fa](https://github.com/hyrathb/mentohust/commit/30198fa4814105f4d5208ba87a8e2e0899fda298)

就是添加了一个判断啊，我觉得只有判断没用啊，还是没有解决需求。

为了紧急需要，我是这样做的：
我是改了`mystate.c`当中的三个包的数值，改成了联通，参考的是：
#282 里面的[改包](www.codingstory.com.cn/mo-gai-mentohust-v4ban-ben-de-xin-de/)


我现在已经在路由器上绑定了MAC地址了，所以没法在本机再测试了

**Comment by updateing** [comment]
`setString()`的调用不是判断啊……它就是写入缓存的。

**Comment by Gabirel** [comment]
我重新看了一下，嗯嗯，我理解错了

**Comment by updateing** [comment]
从命令行过来的中文字总是UTF-8的，要得到GBK只能靠(lib)iconv或者不用中文字直接echo escape string。如果iconv这个程序不能用，那就用echo escape string的方式吧……

如果在程序里加参数进行编码转换的话，得等有时间了加……不过这个要求链接libiconv，这个库在路由上并不常见（更别说默认情况下很可能工具链里有头文件但是没有库导致编译失败），要是自己预先编译libiconv的话，iconv跟着也就出来了。

**Comment by stelectronic** [comment]
@updating 如果在编译mipsel程序时加入了libiconv，编译出来的mentohust大约2.5M，我现在用的就是这个，服务名如果是“外网”的话应该怎么写mentohust参数？

**Comment by Gabirel** [comment]
@stelectronic 有这么大么？我编译出来就103KB

服务名是你往上翻。。。我是通过改程序源代码的形式的，每次按照iconv的方式或者echo escape string的方式太麻烦了

**Comment by stelectronic** [comment]
@Gabirel 可能是路由器不一样，我在ar71xx上编译出来2M多，在mt7628上只有700k。
另外，在哪改代码啊，，如果用iconv呢，又该怎么做，服务名是“外网”

**Comment by Gabirel** [comment]
@stelectronic 
该程序，请参照[这个](https://github.com/hyrathb/mentohust/issues/286#issuecomment-265337108)

使用iconv请参照[这个](https://github.com/hyrathb/mentohust/issues/286#issuecomment-264619528)

**Comment by stelectronic** [comment]
我了解了下载路由器上安装iconv是很麻烦...而且我也不会, 不过既然本项目可以编译时链接libiconv, 而且可以正常运行, 可以不可以利用这个libiconv来转换编码, 而不是利用openwrt的iconv库呢?

**Comment by Gabirel** [comment]
@stelectronic 
1. 路由器上安装iconv其实是很简单的，去openwrt里面对应的固件安装`iconv.ipk`，你安装的时候它会提示你缺少什么依赖，你根据提示就安装对应的ipk就可以了，不用重新编译的。我的解决办法是改包的，[改包点我](http://www.codingstory.com.cn/mo-gai-mentohust-v4ban-ben-de-xin-de/)

2.根据之前提交的issue，可以知道有的服务器不一定是UTF-8的编码的，也有可能是GBK编码形式，我校就是GBK的编码格式。所以你直接在配置文件`mentohust.conf`里面写不一定会对。

> 用户不允许使用本服务

就是代表你们学校的服务器就不是UTF-8编码的。

3.你每次从命令行读入，确实有点麻烦。（新的commit代码好像可以保存了）我没有试过，所以我是改包做的，而且不需要指定`--service`参数。而且，我长期挂在路由器上，网络状态也不会改变，所以对于我自己来说，改包，你自己要看需要

**Comment by stelectronic** [comment]
@Gabirel 

1. 我在openwrt上尝试搜索安装iconv库, 自动安装了三个
iconv_1.11.1-1_ar71xx.ipk. 
libiconv-full_1.11.1-1_ar71xx.ipk.
libcharset_1.11.1-1_ar71xx.ipk.
然而执行iconv -l看到并不支持gbk编码...在网上搜索了下好像openwrt将iconv-full库裁减了, 并没有真正的full...请问你是怎么找到支持GBK的iconv的?

2.我在mentohust.conf里保存service参数是中文gbk编码的"联通"啊, 不是utf8, 而且程序也收到了gbk的"联通", 如上上楼我贴出的信息, 最后好像服务器收到的不是GBK编码, 会不会是程序发送的编码有问题?

3.我下载的12日的源码, 已经可以保存service参数至conf文件

4.改包的链接我看到了, 明天我试一下

finally, 感谢指导!

**Comment by updateing** [comment]
1. 自行编译完整的libiconv十分简单

2. 能在终端上看到“联通”两个字并且其他提示文本都是可读的，就代表着配置文件、serviceName数组以及发出的数据包里都是UTF-8格式的汉字。要是配置文件里是GBK的话，最起码服务名和其他提示文本不可能同时可读

**Comment by Gabirel** [comment]
@stelectronic 巧了，我路由器没有GBK编码，所以我就换了思路，改程序的，哈哈哈～～～毕竟着急用嘛，而且也没有装iconv这种东西。你的第二个问题上楼我想已经回答你了

**Comment by stelectronic** [comment]
@updateing 你是? 

自行编译完整的libiconv哪里简单了, 求教⊙﹏⊙

**Comment by stelectronic** [comment]
@Gabirel 这么晚你也在, 我现在也在尝试改程序, 找到了要改的位置, 是不是只需要改pkt2数组里1a 28 00 00 
13 11 39 22后面四个为就行了?明天重新编译试下^_^(

ps: 你要是知道怎么自行编译完整iconv库可以发我邮箱 o(>﹏<)o

**Comment by Gabirel** [comment]
@stelectronic 三个数组都要改，start, identity和challange包里都要，不然应该是会出错的。

我没那么多时间折腾那个。你交叉编译做过不就知道了

**Comment by stelectronic** [comment]
@updateing 我想了下, 可能是我链接了libiconv库到本程序上, 我的确在conf文件里保存了gbk格式的汉字, 此时在vim界面汉字未正常显示, 程序运行时由于iconv库将gbk转换成了utf-8在终端显示, 此时汉字正常显示, 后面的其他服务器返回的提示文本都正常显示汉字.

说明程序接收到了gbk的汉字, 但是发送给服务器时依然采用utf-8? 如果是这样的情况, 将iconv库也使用到发送给服务器的信息进行转码, 应该就可以解决问题了吧, 这样不用每次改包再编译多麻烦⊙﹏⊙

**Comment by updateing** [comment]
程序不是你想的那样运行，iconv不会自动出来转码……总不能没写的功能凭空就冒出来了吧

从读取配置文件的服务名直到发送都没有任何语句让iconv参与进来，都是直读直写的……这一点自己看代码就行了……

关于vim的乱码，如果你是说路由器上的vim，那很可能它已经被精简到本来就不能显示中文，包括UTF-8

关于iconv，它的编译只会比MentoHUST更简单，先去看它的README再说
