### ISSUE TITLE
请问unsigned char *computeV4(const unsigned char *src, int len);函数的实现逻辑。

### ISSUE THREAD

**Issue by ShanQincheng** [hyrathb/mentohust#299]
你是如何知道有5种情况，并且需要运用多种hash算法来计算那段长度为0x80的加密数据呢？

谢谢。

**Comment by zzuzayu** [comment]
同问该函数。
我自己修改源码之后发现最终还是报不支持的客户端类型。偏移量应该是改对了。
但是认证算法好像用的有问题？
不是有5种case嘛？每次challenge的时候进入的case都不相同。这种情况正常嘛？还是说它读包的偏移量出现了问题。

**Comment by hyrathb** [comment]
这个是我看了前人的代码，然后分析了我们学校客户端得到的。你可以试一试反汇编一下。

**Comment by ShanQincheng** [comment]
谢谢，我了解了。这个算法实在魔幻，我觉得这个项目最精彩的部分就是这里了。
